## **Graduate admission prediction**

### **1. Import libraries**

In [2]:
import warnings
warnings.filterwarnings('ignore')
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import tensorflow as tf

### **2. Load the dataset**

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/update/dl_cnn/1_dl_cnn_basic/data/gpascore.csv')
data

admit    gre   gpa  rank
0        0  380.0  3.21     3
1        1  660.0  3.67     3
2        1  800.0  4.00     1
3        1  640.0  3.19     4
4        0  520.0  2.33     4
..     ...    ...   ...   ...
421      1  750.0  3.44     4
422      1  710.0  3.66     4
423      0  450.0  3.25     4
424      1  760.0  3.76     2
425      1  710.0  3.82     3

[426 rows x 4 columns]

### **3. Explore the data**

In [4]:
data.isnull().sum()

admit    0
gre      1
gpa      0
rank     0
dtype: int64

In [5]:
data.dropna(how='any', inplace=True)

In [6]:
data.isnull().sum()

admit    0
gre      0
gpa      0
rank     0
dtype: int64

### **4. Preprocess the data**

In [7]:
y = data['admit'].values
y[:10]

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 0])

In [8]:
x = []
x_data = data.drop('admit', axis=1)
for i, rows in x_data.iterrows():
    x.append(rows.values)
x[:10]

[array([380.  ,   3.21,   3.  ]),
 array([660.  ,   3.67,   3.  ]),
 array([800.,   4.,   1.]),
 array([640.  ,   3.19,   4.  ]),
 array([520.  ,   2.33,   4.  ]),
 array([760.,   3.,   2.]),
 array([560.  ,   2.98,   1.  ]),
 array([400.  ,   3.08,   2.  ]),
 array([540.  ,   3.39,   3.  ]),
 array([700.  ,   3.92,   2.  ])]

### **5. Build/Compile/Train the model**

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, activation='tanh'),
    tf.keras.layers.Dense(128, activation='tanh'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(np.array(x), y, epochs=1000)

Epoch 1/1000
14/14 [==============================] - 1s 1ms/step - loss: 0.7288 - accuracy: 0.5153
Epoch 2/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6894 - accuracy: 0.5247
Epoch 3/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6814 - accuracy: 0.5365
Epoch 4/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6892 - accuracy: 0.5153
Epoch 5/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.7143 - accuracy: 0.4776
Epoch 6/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6961 - accuracy: 0.5576
Epoch 7/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.7006 - accuracy: 0.5035
Epoch 8/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.5271
Epoch 9/1000
14/14 [==============================] - 0s 2ms/step - loss: 0.6913 - accuracy: 0.5529
Epoch 10/1000
14/14 [==============================] - 0s 1ms/step - loss: 0.6985 - accuracy: 0.5435

### **6. Make predictions**

In [11]:
pred = model.predict([[800, 4.00, 3], [600, 3.00, 1]])
print(np.round(pred, 4))

[[0.9175]
 [0.4357]]
